[package]
name = "umatoi"
version = "0.4.1"
authors = ["yabe_z <Kazuhiro.Yabe@gmail.com>"]
edition = "2021"
license-file = "LICENSE"
keywords = [ "toio", "toio_core_cube" ]
description = "A small library for toio core cube"
repository = "https://github.com/kaz399/umatoi.rs/"
homepage = "https://github.com/kaz399/umatoi.rs/"

[dependencies]
futures = "0.3"
async-trait = "0.1"
thiserror = "2.0"
env_logger = "0.11"
log = "0.4"
uuid = { version = "1.15", features = ["v4"] }
tokio = { version = "1.52", features = ["rt", "rt-multi-thread", "sync", "macros", "signal", "full"] }
btleplug = "0.12"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.20"
byteorder = "1.5"
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = "0.7"

[dev-dependencies]
lazy_static = "1.5"
ctrlc = { version = "3.4", features = ["termination"] }
clap = { version = "4.6", features = ["derive"]}
rand = "0.8"
